name: "Deploy"

on:
   push:
     branches:
       - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    
    - name: execute deploy script on server
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: bash ~/gregslist/update.sh
